#!/bin/sh

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -classic-display \
                          -use-ocamlfind \
                          -plugin-tag package(js_of_ocaml.ocamlbuild)"}

action ()
{
    case $1 in
        default)
            action app
            ;;
        app)
            shift
            $OCAMLBUILD -no-links local.js index.html
            ;;
        clean)
            $OCAMLBUILD -clean ;;
        *)
            $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
